### ISSUE TITLE
Missing values in multRM()

### ISSUE THREAD

**Issue by rmactavi** [smn74/MANOVA.RM#11]
I would like to analyze day of first flowering data on plants in a factorial designed study with drought and nutrient treatments taken across two seasons. Currently, I have the subject(plant), population of origin (lvl = 35), drought (lvl=3), nutrient (lvl=2), season (lvl=2), as independent variables. My dependent variables are height, day of first flower, day of peak flower, and duration of flowering. The data are structured in long format using the timing data, season. I'm running into an issue with the missing data. Flowering data is unequal as populations or treatments resulted in a portion of plants not flowering in either season 1, season 2, or both seasons resulting in missing values and unequal sample structure. 

example data
plant     population  season    drought    nutrient   height    day of first flower  etc.       
1                  23                1            high           high       15.6                 125
2                  23               1             low            high        20.7                50
3                  15               1              low            low         11.7                 67
4                  15               1             high            high         NA                 NA

1                  23               2            high            high          8.7                33
2                  23               2            low              high        5.2                 45
3                  15               2             low            low          NA                  NA
4                  15              2             high           high         35                  72

I tried accounting for missing data by dropping incomplete cases before running multRM(). I get the error below, does it mean that there are unequal sample sizes?

"Error in prepare.data(formula, data, subject, within) : 
  The number of subjects (971) times the 
  number of within-subject factor levels (2) does not equal
  the total number of observations (1443). 
  Check for missing values in the data."

Do you know if repeated measures multivariate approach with multRM with work with this missing data?

Thank you so much for your help. 
Rachel

**Comment by smn74** [comment]
Hi Rachel,
the error means that there are still some missing values in your data. For multRM to work, each subject must be observed at all time points (seasons in your example). Unfortunately, an approach that works for missing data is not implemented yet.
Best,
Sarah
