### ISSUE TITLE
Can't get resampled p values from oneway MANOVA

### ISSUE THREAD

**Issue by jszczypinski** [smn74/MANOVA.RM#12]
Hi,
I am running a post-hoc univariate models as showed in the vignette here:
https://rdrr.io/cran/MANOVA.RM/f/vignettes/Introduction_to_MANOVA.RM.Rmd

My model specification is:
`rm1 = MANOVA (dv ~ species, data = data, iter = 1000, seed = 2137, subject = 'id', resampling = "paramBS")`
I am estimating four similar models for post-hoc analysis, and I would like to get resampled p values for Holm's adjustment.
However, the `rm1$resampling` returns only 0s when p values are lower than p < 0.001.

I tried to change `dec` parameter, but without any success.
Is there any way to get these p values?

Best,
Jan

**Comment by smn74** [comment]
With the resampled p-values, it can happen that they are numerically exactly 0. The number of decimals on the p-values depends on the number of resampling iterations, i.e. you can increase this number by increasing "iter" and "dec" simultaneously. Perhaps that helps?
