### ISSUE TITLE
factor selection in simCI does not work

### ISSUE THREAD

**Issue by teindor** [smn74/MANOVA.RM#13]
Hi
I used the following code for MultiRM:
ma3 = multRM(cbind(com_h, com_w,sup_h,sup_w,res_h,neg_h,pos_h,co_h,res_w,neg_w,pos_w,co_w)~C*time,
                  data = long, resampling = "WildBS", para = T, CPU = 10, subject = "ID", within = "time", iter = 1000)
Because the multivariate was significant I followed it by:
ma3_1 = multRM(com_h~C*time,data = long, resampling = "WildBS", para = T, CPU = 10, subject = "ID", within = "time", iter = 1000)
and then:
simCI(ma3_1, contrast = "pairwise", type = "Tukey", interaction = F, factor = C)

The last line of code does not work and produce the following error:

Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
In addition: Warning message:
In is.na(factor) :
  is.na() applied to non-(list or vector) of type 'closure'

It does work without the "interaction = F, factor = C". I tried to state the name of factor in various ways, without help.
Any suggestions?

> version
               _                           
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.2                         
year           2021                        
month          11                          
day            01                          
svn rev        81115                       
language       R                           
version.string R version 4.1.2 (2021-11-01)
nickname       Bird Hippie

**Comment by smn74** [comment]
Hi,
the simCI-function currently only works for MANOVA, but not for RM-designs. I plan to change that in the future, but... ;-) Anyway, I have now added a more comprehensive error message for this situation.
Best, Sarah
