### ISSUE TITLE
Including Continuous Independent Variable into repeated measures MANOVA using MultRM function?

### ISSUE THREAD

**Issue by danielazarate** [smn74/MANOVA.RM#14]
Hello, 

I am trying to run a repeated measure MANOVA in R, with three independent variables and seven dependent variables. 

Independent Variable 1 is categorical with two levels. 
Independent Variable 2 is continuous. 
Independent Variable 3 is my within-subjects variable and corresponds to the time the data was collected. 

fit <- multRM(cbind(DV1, DV2, DV3, DV4, DV5. DV6. DV7) 
                ~ IV1 * IV2 * TIME, data = df1, subject = "ID", within = "TIME", iter = 1000)

My data has no missing data. 

Upon running this command, I get the error message:

Error in prepare.data(formula, data, subject, within) : 
  There is at least one factor-level combination
           with less than 2 observations!
In addition: There were 47 warnings (use warnings() to see them)

Warning messages:
1: In matrix(t(x), nrow = nrow(x)/prod(fl[within]), ncol = p *  ... :
  data length exceeds size of matrix

The IV 3 continuous data is of numeric class. 

I think that perhaps the multRM function is not registering the continuous data as continuous data and because all the continuous data is unique, it is assuming that it is categorical data with a huge number of factor levels. 

My question is whether multRM can handle both independent variable of continuous and categorical data and if so, is there a specific way to structure it so that the function recognizes it as such? 

Thank you very much.

**Comment by smn74** [comment]
Hi,
that's right, the RM and MANOVA function are only working in an ANOVA-like setting, so all independent variables have to be categorical. Otherwise, you're looking for an ANCOVA-model, where a mixture of factors and continuous predictors is possible. This is not implemented in MANOVA.RM.
