### ISSUE TITLE
Missing values in the data

### ISSUE THREAD

**Issue by bkhow** [smn74/MANOVA.RM#3]
I've had an issue with the RM() function with an error:

Error in RM(Flux ~ ESD * Burn * Time, subject = "Trap", data = nodrill) : 
  There are missing values in the data.

There are no missing values in my datasets. In the past I've had to export a csv, copy into a text file and reimport and this would fix the issue. However this work around isn't helping today.

[nodrill.txt](https://github.com/smn74/MANOVA.RM/files/4331149/nodrill.txt)

Any advice?

**Comment by smn74** [comment]
Thanks for your message and especially for providing your data! That makes it so much easier to spot a problem. The point is that there are missing values in your data in the sense that you don't have observations from every subject at every time point (e.g. for trap 2, time 2 is missing). RM can so far only handle designs where the time points are the same for all individuals. I am working on extensions of this and I will make the error message more comprehensive.
Thanks again for pointing that out to me!
Sarah

**Comment by goodwi27** [comment]
Dr Friedrich, I am having trouble with this error using the RM command. The time points are the same for all individuals in our dataset, so we have no missing data. Please let me know if I can provide more information. Thanks.

**Comment by goodwi27** [comment]
Hi - I think I fixed things. Making sure my dataset was structured as a data frame helped (using the as.data.frame command). May be a basic thing to check that I didn't think of until later, but thought I would post here in case it helps anyone else!

**Comment by eler20** [comment]
Hi Sarah,
I was wondering whether it is now possible to apply multRM on data with missing values in the sense you described above (some subjects do not have observations for every time point) as I am experiencing some function behavior I cannot really explain. 
I have a 3 x 3 design (between x subject) and first I excluded almost all datasets for which one time point was missing. I forgot one dataset which had only two instead of three observations, but multRM still worked. If I now include all datasets with time points missing, I get the following error:

```
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: nicht passende Argumente
In addition: Warning message:
In matrix(t(x), nrow = nrow(x)/prod(fl[within]), ncol = p * prod(fl[within]),  :
  data length [210] is not a sub-multiple or multiple of the number of rows [11]
```

And also I noticed that the displayed "n" of the descriptive of multRM seems off to me. For me, the number is equal amongst the within subject factors but not the between subject factors. I would expect the amount of datasets to be equal regarding the within subject factors for a fixed between subject factor as I just removed all data sets which do not have observations for all time points. Do you have any advice for the two issues?

Many thanks in advance and kind regards!

**Comment by smn74** [comment]
Hi,
no, it still shouldn't be possible to apply multRM with an unequal number of measurements. I don't know what happened there... The displayed n should be for the combinations of the between subject factors, since the within should then be the same for all individuals (assuming no missing data as mentioned above). A problem might be that if you do have missing data, but such that it adds up again in the end, the measurement get mixed up (do you know what I mean?) I'll try to build an example to reproduce your problem.
Best,
Sarah

**Comment by eler20** [comment]
Hi Sarah,
thanks for your reply! I understand what you meant regarding that missing data might in the end add up to an amount that is a multiple and the measurements get mixed up. Should the n of the within subject factors be equal within a fixed between subject factor or overall? 
Maybe it helps if I describe my observation regarding the "n" more in detail? I now removed all individuals which have a missing value in some of the within subject factors and I had then 21 measurements in all within subject factors for group 1, 19 for group 2 and 11 for group 3. These were the displayed descriptives:
`Descriptives:
group 1 - within 1: n = 21 
group 1 - within 2: n = 19
group 1 - within 3: n = 11
group 2 - within 1: n = 21
group 2 - within 2: n = 19
group 2 - within 3: n = 11
group 3 - within 1: n= 21
group 3 - within 2: n = 19
group 3 - within 3: n = 11
`
If I understood correctly, the n should be 21 for all three levels of group 1, 19 for all levels of group 2 and 11 for all levels of group 3, right? Does the displayed n influence the algorithm or can I still assume that my comparisons are calculated correctly?

**Comment by smn74** [comment]
Yes, that's right, the n should be 21 for all three levels of group 1, 19 for the levels of group 2 and so on. How does your formula look? Is the within-factor the last factor specified?

**Comment by eler20** [comment]
Yes, the within-factor is the last factor specified:
`dependent_variable ~ between_subject * within_subject`
Do you think that the results are still correct even though the n values are off?

**Comment by smn74** [comment]
No, if the n values are sorted wrong then so are probably the means. Is it possible that you provide me with your data or a part of it so I can try to find the error?

**Comment by jrogawa** [comment]
> Hi - I think I fixed things. Making sure my dataset was structured as a data frame helped (using the as.data.frame command). May be a basic thing to check that I didn't think of until later, but thought I would post here in case it helps anyone else!

Hi there.

I would urge you, Dr. Friedrich, to please put a check and corresponding error in at least RM for data that is not in data.frame format. I spent a non-trivial amount of time getting the "missing values" error until I converted my data in tibble format to a data.frame. :-)

Thank you so much for this package!

**Comment by smn74** [comment]
Thank you for pointing that out! I hadn't considered that length() doesn't work for a column extracted from a tibble. It should be fixed now :-)

**Comment by jrogawa** [comment]
No problem! Thank YOU for creating it and taking the trouble to put it out there!

**Comment by jgacnik** [comment]
Hi Sarah @smn74 ,
I am trying to use the MANOVA.RM on my dataset (attached)
[TD data.csv](https://github.com/smn74/MANOVA.RM/files/11425894/TD.data.csv)

The code is:
data <- read.csv("TD data.csv")
dependent_vars <- cbind(data$O, data$Br_Cl, data$N, data$S, data$Org)
RM_MANOVA_model <- RM(dependent_vars ~ Date * Flow, data = data,
                      subject = "Date", no.subf = 2, iter = 1000,
                      resampling = "Perm", seed = 1234)

I keep getting the error:  The number of subjects (15) times the number of within-subject factor levels (30) does not equal the total number of observations (30). Check for missing values in the data.

Any suggestions? I don't have any missing data and I think it is just something wrong with my code. I am a bit lost. Any help would be greatly appreciated!

**Comment by smn74** [comment]
Hi,

you want to fit a RM model with several dependent variables, so you need 
to use multRM(cbind(...) ~ ...). That should hopefully solve the problem :-)

Best,

Sarah

Am 09.05.23 um 10:37 schrieb GacoMaco:

**Comment by jrogawa** [comment]
Hey Sarah.

Wow. I forgot all about this thread!

It is so great of you to continue to put in the effort to answer questions!

I have a small piece of code that I have never released because I don’t want to have to deal with problems that will come up from it! 😊

Continued thank you!

J

**Comment by jgacnik** [comment]
Thank you @smn74 !
Now I run into the error ""Error in prepare.data(formula, data, subject, within): There is at least one factor-level combination with less than 2 observations!""

The data is the same, the code goes as follows:
data <- read.csv("TD data.csv")
dependent_vars <- cbind(data$O, data$Br_Cl, data$N, data$S, data$Org)
RM_MANOVA_model <- multRM(dependent_vars ~ Date * Flow, data = data,
                      subject = "Date", within = "Flow", iter = 1000, seed = 1234)

Sorry for the trouble, but I will make sure to cite your work if I manage to make this work :)

**Comment by smn74** [comment]
Hi,

if "Date" is your subject variable, you don't need to treat it as a 
factor. If I understood the data structure correctly, you only have one 
within-subject factor "Flow" with two levels, right? Then the code would 
read

RM_MANOVA_model <- multRM(dependent_vars ~ Flow, data = data,
subject = "Date", within = "Flow", iter = 1000, seed = 1234)

Hope that helps!

Sarah

Am 09.05.23 um 19:13 schrieb GacoMaco:

**Comment by jgacnik** [comment]
That worked! Thank you a lot @smn74 , thank you for making this package. It still seems to be the only useful package for repeated measures MANOVA in R :)
