### ISSUE TITLE
Function simCI: Wrong value to arg. select in call to subset

### ISSUE THREAD

**Issue by GerritEichner** [smn74/MANOVA.RM#4]
In function simCI of version 0.3.4 the code line
lev <- subset(object$Descriptive, select = 1:n)
is wrong from my point of view. The value for argument
select should rather be 1:nf, i.e.:
lev <- subset(object$Descriptive, select = 1:nf)

**Comment by smn74** [comment]
Thanks for pointing that out! It's corrected now.
