### ISSUE TITLE
MANOVA.RM post-hoc Error in if (object$nested) { : argument is of length zero

### ISSUE THREAD

**Issue by albaperis** [smn74/MANOVA.RM#6]
Hi,
I used the packacge RM.ANOVA to run my repeated measures multivariate anova and saved it in model1.

model1<-RM(A~exp*Od*PvN, data=allA,
           subject='subject', no.subf=2, iter=10000,
           resampling='paramBS')
summary(model1)
The factor PvN has a significant main-effect, therefore I would like to run post-hoc tests, so I tried:

simCI(model1,contrast('pairwise'),type='Tukey',interaction='FALSE', factor='PvN')
However, this error message comes up: Error in if (object$nested) { : argument is of length zero

Would it be possible to know how I can run post-hoc tests in my model on the main effects and the interactions(given they were significant). Thanks you very much!

**Comment by smn74** [comment]
Hi,
simCI currently only works for MANOVA, I have not yet implemented post-hoc test for repeated measures. Thanks for pointing me to that misleading error message, though, I have no included a more helpful one :-)
Best,
Sarah
