### ISSUE TITLE
MultRM without between subject factor

### ISSUE THREAD

**Issue by tomnqian** [smn74/MANOVA.RM#8]
When trying to test a within-subject only design with repeated multivariate measures, such as `fit <- multRM(cbind(brainrate, complexity) ~  region, data = eeg, subject = "id", within = "region", iter = 200, CPU = 1)`  
(The eeg dataset is created following the vignette for this package. I only took out sex from the model.)

I received this message `Error in if (nrow(data)/length(unique(subject)) != prod(fl[within])) { : 
  missing value where TRUE/FALSE needed`

Thank you very much for the help and great work!

**Comment by smn74** [comment]
Thanks for your comment! Have you tried with the latest version? Cause it works fine on my system...
