### ISSUE TITLE
RM ANOVA on non-parametric data

### ISSUE THREAD

**Issue by albaperis** [smn74/MANOVA.RM#9]
Hi, 

I am trying to run a RM ANOVA but my DV is not normally distributed. I therefore was trying to use the RM() function in your package. Would this be correct?

I tried running the following:

model<-RM(DV~ IV1*IV2, subject='subject', no.subf=2, data = df, resampling='paramBS')

Where subject is the name of my subject column list, and no.subf is the number of within-subject factors (i.e IV1, IV2). However I get the following error:

Error in A %*% x : non-conformable arguments

Do you have some guidance on how to proceed? 

Thanks!

**Comment by smn74** [comment]
Thank you for your comment! Yes, the RM function is suitable for non-normally distributed DVs, as long as they are measured on a metric scale. Without actually seeing the data, it's difficult for me to diagnose what the problem might be. You don't have any missing values in your data? Did you observe your outcome for every combination of IV1 and IV2?
